config/routes.rb
Rails.application.routes.draw do
   root 'tweets#index'
   resources :tweets, only: [:create, :index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
require 'net/http'
require 'uri'
require 'pry'
require 'json'

class TweetsController < ApplicationController

  before_action :set_data, only: [:destroy]

  def index
    @tweet = Tweet.new
    @tweets = Tweet.all
  end

  def create
    # 緯度経度情報を元にgoogleplacesAPIを用いて、周辺の施設を検索
    # 施設情報の中からランダムで１つ抽出し、並べる
    @tweet = Tweet.new(tweet_params)
    @tweet.save

    googleplacesAPI = ENV['googlePlacesAPIKey']

    lat = @tweet.latitude
    lng = @tweet.longitude

    rad = 2000
    language = 'ja'

    places = [ ["restaurant"], ["aquarium", "park", "museum", "shopping_mall"], ["cafe"] ]

    @result_places = []
    places.each do |place|
      types = place[rand(place.length)]

      url = URI.parse(URI.escape("https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=#{lat},#{lng}&radius=#{rad}&types=#{types}&sensor=false&language=ja&key=#{googleplacesAPI}"))
      res = Net::HTTP.start(url.host, url.port, use_ssl: true) { |http|
        http.get(url.path + '?' + url.query);
      }

      obj = JSON.parse(res.body)

      @result_places << obj["results"][rand(obj["results"].length)]["name"]
    end

    respond_to do |format|
      format.html { redirect_to controller: 'tweets', action: 'index' }
      format.json
    end
  end

  # objのresultsキーの0番目の配列の要素の中のnameキーを取得する
  # obj["results"][0]["name"]

  def destroy
    @tweet.destroy
    redirect_to root_path
  end

  private
    def set_data
      @tweet = Tweet.find(params[:id])
    end

    def tweet_params
      params.require(:tweet).permit(:address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DatePlaner</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/index.html.erb
<div class="container">

  <div class="result">
  </div>

  <div class="comments">
    <% @tweets.each do |tweet| %>
      <div class="section clearfix">
        <p class="tweet_field"><%= tweet.address %></p>
        <%= link_to "削除", tweet_path(tweet), method: :delete,  class: "btn button" %>
      </div>
      <div class="divider last"></div>
    <% end %>
  </div>

  <div class="comment_form">
    <%= form_for @tweet, html: {id: 'item_form'} do |f| %>
      <div class="row">
        <div class="col s12">
          <div class="row">
            <h3>デート場所を検索してみよう</h3>
            <div class="input-field col s12">
              <i class="material-icons prefix">textsms</i>
              <%= f.text_field :address, id: "autocomplete-input", class: "autocomplete, message", placeholder: "デート場所を入力してみて" %>
              <% f.label "Autocomplete", for: "autocomplete-input" %>
            </div>
          </div>
        </div>
      </div>

      <%= f.submit "Submit", class: "btn waves-effect waves-light", id: "message_submit", name: "action" %>
    <% end %>
  </div>
</div>


<script type="text/javascript">
  $(function() {
    function buildHTML(tweet) {
      var html = `
                  <div class="section clearfix">
                    <p class="tweet_field">${tweet.address}</p>
                    <a data-confirm="削除しますか？" data-method="delete" href="/tweets/${tweet.id}" rel="nofollow" class="btn button">削除</a>
                  </div>
                 `
      return html
    }
    function buildResult(tweet) {
      var html2 = `
                  <div class="divider"></div>
                  <div class="section clearfix">
                    <p class="tweet_field">デートプラン<br>【昼】${tweet.place1}<br>【夕方】${tweet.place2}<br>【夜】${tweet.place3}</p>
                  </div>
                  <div class="divider"></div>
                 `
      return html2
    }

    $('#item_form').on("submit", function(e) {
      e.preventDefault();
      var formData = new FormData(this);
      var url = $(this).attr('action');
      $.ajax({
        url: url,
        type: 'POST',
        data: formData,
        dataType: 'json',
        processData: false,
        contentType: false,
        success: function(data){
          if (data.place1) {
            var html = buildHTML(data);
            var html2 = buildResult(data);
            $('.comments').append(html);
            $('.comments').append(html2);
            $('.message').val('');
            // location.reload();
          } else {
            var html2 = buildHTML(data);
            $('.comments').append(html);
            $('.message').val('');
            // location.reload();
          }
        }
      });
    });
  });
</script>